services:
  # 1. The Main Bot (The one that sends PDFs)
  - type: web
    name: krok-main-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: ALLOWED_USER_ID
        value: 7349230382

  # 2. The Password Bot (The new one)
  - type: worker
    name: krok-password-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python password_bot.py
    envVars:
      - key: ALLOWED_USER_ID
        value: 7349230382
